In [1]:
#import the necessary packages for dealing with the data in a dataframe (pandas and numpy). Additionally
#import IPython.display, which will allow the entire width od the df to be displayed.
import pandas as pd
import numpy as np
from IPython.display import display

In [2]:
loans = pd.read_csv('loan.csv', nrows = 10)
pd.options.display.max_columns = None
display(loans)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500,36 months,13.56,84.92,C,C1,Chef,10+ years,RENT,55000,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,109xx,NY,18.24,0,Apr-2001,1,NaN,45.0,9,1,4341,10.3,34,w,2386.02,2386.02,167.02,167.02,113.98,53.04,0.0,0.0,0.0,Feb-2019,84.92,Mar-2019,Feb-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,16901,2,2,1,2,2,12560,69.0,2,7,2137,28,42000,1,11,2,9,1878,34360.0,5.9,0,0,140,212,1,1,0,1.0,NaN,2,NaN,0,2,5,3,3,16,7,18,5,9,0,0,0,3,100.0,0.0,1,0,60124,16901,36500,18124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000,60 months,18.94,777.23,D,D2,Postmaster,10+ years,MORTGAGE,90000,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,713xx,LA,26.52,0,Jun-1987,0,71.0,75.0,13,1,12315,24.2,44,w,29387.75,29387.75,1507.11,1507.11,612.25,894.86,0.0,0.0,0.0,Feb-2019,777.23,Mar-2019,Feb-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,1208,321915,4,4,2,3,3,87153,88.0,4,5,998,57,50800,2,15,2,10,24763,13761.0,8.3,0,0,163,378,4,3,3,4.0,NaN,4,NaN,0,2,4,4,9,27,8,14,4,13,0,0,0,6,95.0,0.0,1,0,372872,99468,15000,94072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000,36 months,17.97,180.69,D,D1,Administrative,6 years,MORTGAGE,59280,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,490xx,MI,10.51,0,Apr-2011,0,NaN,NaN,8,0,4599,19.1,13,w,4787.21,4787.21,353.89,353.89,212.79,141.10,0.0,0.0,0.0,Feb-2019,180.69,Mar-2019,Feb-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,110299,0,1,0,2,14,7150,72.0,0,2,0,35,24100,1,5,0,4,18383,13800.0,0.0,0,0,87,92,15,14,2,77.0,NaN,14,NaN,0,0,3,3,3,4,6,7,3,8,0,0,0,0,100.0,0.0,0,0,136927,11749,13800,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4000,4000,4000,36 months,18.94,146.51,D,D2,IT Supervisor,10+ years,MORTGAGE,92000,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,985xx,WA,16.74,0,Feb-2006,0,NaN,NaN,10,0,5468,78.1,13,w,3831.93,3831.93,286.71,286.71,168.07,118.64,0.0,0.0,0.0,Feb-2019,146.51,Mar-2019,Feb-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,686,305049,1,5,3,5,5,30683,68.0,0,0,3761,70,7000,2,4,3,5,30505,1239.0,75.2,0,0,62,154,64,5,3,64.0,NaN,5,NaN,0,1,2,1,2,7,2,3,2,10,0,0,0,3,100.0,100.0,0,0,385183,36151,5000,44984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000,60 months,16.14,731.78,C,C4,Mechanic,10+ years,MORTGAGE,57250,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,212xx,MD,26.35,0,Dec-2000,0,NaN,NaN,12,0,829,3.6,26,w,29339.02,29339.02,1423.21,1423.21,660.98,762.23,0.0,0.0,0.0,Feb-2019,731.78,Mar-2019,Feb-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,116007,3,5,3,5,4,28845,89.0,2,4,516,54,23100,1,0,0,9,9667,8471.0,8.9,0,0,53,216,2,2,2,2.0,NaN,13,NaN,0,2,2,3,8,9,6,15,2,12,0,0,0,5,92.3,0.0,0,0,157548,29674,9300,32332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,5550,5550,5550,36 months,15.02,192.45,C,C3,Director COE,10+ years,MORTGAGE,152500,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,461xx,IN,37.94,0,Sep-2002,3,NaN,NaN,18,0,53854,48.1,44,w,5302.50,5302.50,377.95,377.95,247.50,130.45,0.0,0.0,0.0,Feb-2019,192.45,Mar-2019,Feb-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,685749,1,7,2,3,4,131524,72.0,1,4,17584,58,111900,2,4,6,8,40338,23746.0,64.0,0,0,195,176,10,4,6,20.0,NaN,3,NaN,0,4,6,6,10,23,9,15,7,18,0,0,0,4,100.0,60.0,0,0,831687,185378,65900,203159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,2000,2000,2000,36 months,17.97,72.28,D,D1,Account Manager,4 years,RENT,51000,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,606xx,IL,2.40,0,Nov-2004,1,NaN,NaN,1,0,0,NaN,9,w,1914.71,1914.71,141.56,141.56,85.29,56.27,0.0,0.0,0.0,Feb-2019,72.28,Mar-2019,Feb-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,854,0,0,2,3,7,0,NaN,0,1,0,100,0,0,0,1,4,854,NaN,NaN,0,0,169,40,23,7,0,NaN,NaN,1,NaN,0,0,0,0,3,5,0,3,0,1,0,0,0,2,100.0,NaN,0,0,854,854,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,6000,6000,6000,36 months,13.56,203.79,C,C1,Assistant Director,10+ years,RENT,65000,Source Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,460xx,IN,30.10,0,Nov-1997,0,NaN,NaN,19,0,38476,69.3,37,w,5864.01,5864.01,201.53,201.53,135.99,65.54,0.0,0.0,0.0,Feb-2019,208.31,Mar-2019,Feb-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,91535,0,5,0,1,23,53059,87.0,0,2,9413,74,55500,1,2,0,3,5085,3034.0,90.8,0,0,169,253,13,13,1,14.0,NaN,13,NaN,0,7,12,8,10,15,14,20,12,19,0,0,0,0,100.0,85.7,0,0,117242,91535,33100,61742,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DirectPay,N,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,5000,5000,5000,36 months,17.97,180.69,D,D1,Legal Assistant III,10+ years,MORTGAGE,53580,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,327xx,FL,21.16,0,Aug-1998,1,32.0,NaN,8,0,8018,35.2,38,w,4786.79,4786.79,353.89,353.89,213.21,140.68,0.0,0.0,0.0,Feb-2019,180.69,Mar-2019,Feb-2019,0,45.0,1,Individual,NaN,NaN,NaN,0,0,41882,5,2,5,5,3,33864,98.0,1,6,3132,73,22800,2,1,4,12,5235,13786.0,35.9,0,0,145,244,6,3,3,6.0,33.0,2,32.0,2,4,5,5,10,20,6,15,5,8,0,0,0,6,78.9,60.0,0,0,57426,41882,21500,34626,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,6000,6000,6000,36 months,14.47,206.44,C,C2,NaN,< 1 year,OWN,300000,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,068xx,CT,17.43,1,Apr-2002,1,17.0,NaN,38,0,65950,49.8,58,w,5730.20,5730.20,405.64,405.64,269.80,135.84,0.0,0.0,0.0,Feb-2019,206.44,Mar-2019,Feb-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,349502,1,4,1,3,7,39961,45.0,1,12,15926,48,132500,2,2,2,15,9197,38683.0,60.6,0,0,166,200,4,4,1,4.0,NaN,4,17.0,0,16,20,19,26,9,33,48,20,38,0,0,0,2,100.0,26.3,0,0,477390,105911,98300,89600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#take the list of all columns, and remove the columns that are not useful to this ml model
keep = ['loan_amnt','term','installment','emp_length',
        'home_ownership','annual_inc', 'loan_status','purpose','dti',
        'delinq_2yrs','inq_last_6mths','mths_since_last_delinq','mths_since_last_record','open_acc',
        'pub_rec','revol_bal','revol_util','total_acc',
        'total_rec_prncp','total_rec_int','total_rec_late_fee',
        'recoveries','collection_recovery_fee','collections_12_mths_ex_med','mths_since_last_major_derog',
        'application_type','acc_now_delinq','tot_coll_amt','tot_cur_bal','open_acc_6m',
        'open_act_il','open_il_12m','open_il_24m','mths_since_rcnt_il','total_bal_il','il_util','open_rv_12m',
        'open_rv_24m','max_bal_bc','all_util','total_rev_hi_lim','inq_fi','total_cu_tl','inq_last_12m',
        'acc_open_past_24mths','avg_cur_bal','bc_open_to_buy','bc_util','chargeoff_within_12_mths','delinq_amnt',
        'mo_sin_old_il_acct','mo_sin_old_rev_tl_op','mo_sin_rcnt_rev_tl_op','mo_sin_rcnt_tl','mort_acc',
        'mths_since_recent_bc','mths_since_recent_bc_dlq','mths_since_recent_inq',
        'mths_since_recent_revol_delinq','num_accts_ever_120_pd','num_actv_bc_tl','num_actv_rev_tl',
        'num_bc_sats','num_bc_tl','num_il_tl','num_op_rev_tl','num_rev_accts','num_rev_tl_bal_gt_0','num_sats',
        'num_tl_120dpd_2m','num_tl_30dpd','num_tl_90g_dpd_24m','num_tl_op_past_12m','pct_tl_nvr_dlq',
        'percent_bc_gt_75','pub_rec_bankruptcies','tax_liens','tot_hi_cred_lim','total_bal_ex_mort',
        'total_bc_limit','total_il_high_credit_limit']

loans = pd.read_csv('loan.csv', usecols = keep)

loans = loans[loans['application_type']=='Individual']

pd.options.display.max_columns = None
display(loans)

,loan_amnt,term,installment,emp_length,home_ownership,annual_inc,loan_status,purpose,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,mths_since_last_major_derog,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,2500,36 months,84.92,10+ years,RENT,55000.0,Current,debt_consolidation,18.24,0.0,1.0,NaN,45.0,9.0,1.0,4341,10.3,34.0,113.98,53.04,0.0,0.0,0.0,0.0,NaN,Individual,0.0,0.0,16901.0,2.0,2.0,1.0,2.0,2.0,12560.0,69.0,2.0,7.0,2137.0,28.0,42000.0,1.0,11.0,2.0,9.0,1878.0,34360.0,5.9,0.0,0.0,140.0,212.0,1.0,1.0,0.0,1.0,NaN,2.0,NaN,0.0,2.0,5.0,3.0,3.0,16.0,7.0,18.0,5.0,9.0,0.0,0.0,0.0,3.0,100.0,0.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0
1,30000,60 months,777.23,10+ years,MORTGAGE,90000.0,Current,debt_consolidation,26.52,0.0,0.0,71.0,75.0,13.0,1.0,12315,24.2,44.0,612.25,894.86,0.0,0.0,0.0,0.0,NaN,Individual,0.0,1208.0,321915.0,4.0,4.0,2.0,3.0,3.0,87153.0,88.0,4.0,5.0,998.0,57.0,50800.0,2.0,15.0,2.0,10.0,24763.0,13761.0,8.3,0.0,0.0,163.0,378.0,4.0,3.0,3.0,4.0,NaN,4.0,NaN,0.0,2.0,4.0,4.0,9.0,27.0,8.0,14.0,4.0,13.0,0.0,0.0,0.0,6.0,95.0,0.0,1.0,0.0,372872.0,99468.0,15000.0,94072.0
2,5000,36 months,180.69,6 years,MORTGAGE,59280.0,Current,debt_consolidation,10.51,0.0,0.0,NaN,NaN,8.0,0.0,4599,19.1,13.0,212.79,141.10,0.0,0.0,0.0,0.0,NaN,Individual,0.0,0.0,110299.0,0.0,1.0,0.0,2.0,14.0,7150.0,72.0,0.0,2.0,0.0,35.0,24100.0,1.0,5.0,0.0,4.0,18383.0,13800.0,0.0,0.0,0.0,87.0,92.0,15.0,14.0,2.0,77.0,NaN,14.0,NaN,0.0,0.0,3.0,3.0,3.0,4.0,6.0,7.0,3.0,8.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,136927.0,11749.0,13800.0,10000.0
3,4000,36 months,146.51,10+ years,MORTGAGE,92000.0,Current,debt_consolidation,16.74,0.0,0.0,NaN,NaN,10.0,0.0,5468,78.1,13.0,168.07,118.64,0.0,0.0,0.0,0.0,NaN,Individual,0.0,686.0,305049.0,1.0,5.0,3.0,5.0,5.0,30683.0,68.0,0.0,0.0,3761.0,70.0,7000.0,2.0,4.0,3.0,5.0,30505.0,1239.0,75.2,0.0,0.0,62.0,154.0,64.0,5.0,3.0,64.0,NaN,5.0,NaN,0.0,1.0,2.0,1.0,2.0,7.0,2.0,3.0,2.0,10.0,0.0,0.0,0.0,3.0,100.0,100.0,0.0,0.0,385183.0,36151.0,5000.0,44984.0
4,30000,60 months,731.78,10+ years,MORTGAGE,57250.0,Current,debt_consolidation,26.35,0.0,0.0,NaN,NaN,12.0,0.0,829,3.6,26.0,660.98,762.23,0.0,0.0,0.0,0.0,NaN,Individual,0.0,0.0,116007.0,3.0,5.0,3.0,5.0,4.0,28845.0,89.0,2.0,4.0,516.0,54.0,23100.0,1.0,0.0,0.0,9.0,9667.0,8471.0,8.9,0.0,0.0,53.0,216.0,2.0,2.0,2.0,2.0,NaN,13.0,NaN,0.0,2.0,2.0,3.0,8.0,9.0,6.0,15.0,2.0,12.0,0.0,0.0,0.0,5.0,92.3,0.0,0.0,0.0,157548.0,29674.0,9300.0,32332.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260662,30000,60 months,984.47,6 years,MORTGAGE,100000.0,Current,debt_consolidation,22.13,0.0,2.0,NaN,NaN,9.0,0.0,19206,66.9,14.0,4201.22,11422.18,0.0,0.0,0.0,0.0,NaN,Individual,0.0,776.0,174805.0,2.0,3.0,1.0,3.0,3.0,49474.0,77.0,1.0,3.0,9558.0,74.0,28700.0,3.0,4.0,3.0,7.0,19423.0,6942.0,57.9,0.0,0.0,37.0,253.0,6.0,3.0,2.0,26.0,NaN,4.0,NaN,0.0,1.0,2.0,2.0,4.0,4.0,5.0,8.0,2.0,9.0,0.0,0.0,0.0,3.0,100.0,50.0,0.0,0.0,201286.0,68680.0,16500.0,64086.0
2260663,12000,60 months,279.72,10+ years,MORTGAGE,58000.0,Current,debt_consolidation,20.88,0.0,0.0,NaN,NaN,12.0,0.0,9592,39.2,34.0,3312.80,2048.16,0.0,0.0,0.0,0.0,NaN,Individual,0.0,7921.0,45212.0,2.0,2.0,0.0,1.0,24.0,35620.0,36.0,3.0,4.0,4052.0,38.0,24500.0,2.0,2.0,1.0,5.0,4110.0,1807.0,70.9,0.0,0.0,157.0,164.0,1.0,1.0,2.0,9.0,NaN,9.0,NaN,0.0,2.0,4.0,3.0,9.0,11.0,10.0,21.0,4.0,12.0,0.0,0.0,0.0,3.0,100.0,66.7,0.0,0.0,73948.0,45212.0,6200.0,49448.0
2260665,10000,36 months,332.10,10+ years,OWN,64000.0,Current,debt_consolidation,12.96,0.0,0.0,NaN,NaN,6.0,0.0,7094,70.9,13.0,4006.73,1300.21,0.0,0.0,0.0,1.0,NaN,Individual,0.0,77.0,189735.0,1.0,2.0,1.0,2.0,3.0,29354.0,100.0,0.0,1.0,1864.0,93.0,10000.0,0.0,0.0,3.0,3.0,31623.0,136.0,93.2,0.0,0.0,134.0,271.0,15.0,3.0,3.0,111.0,NaN,3.0,NaN,0.0,1.0,3.0,1.0,2.0,4.0,3.0,6.0,3.0,6.0,0.0,0.0,0.0,1.0,100.0,100.0,0.0,0.0,203417.0,36448.0,2000.0,29317.0
2260666,12000,60 months,327.69,NaN,RENT,60000.0,Current,debt_consolidation,30.82,2.0,1.0,7.0,NaN,8.0,0.0,12927,34.9,17.0,2075.31,3131.98,0.0,0.0,0.0,0.0,NaN,Individual,0.0,535.0,65238.0,2.0,4.0,2.0,3.0,4.0,52311.0,64.0,1.0,2.0,2406.0,55.0,37000.0,0.0,12.0,4.0,5.0,8155.0,18789.0,14.6,0.0,0.0,170.0,67.0,4.0,4.0,0.0,16.0,9.0,5.0,7.0,0.0,2.0,3.0,2.0,3.0,12.0,4.0,5.0,3.0,8.0,0.0,0.0,0.0,3.0,88.2,0.0,0.0,0.0,118975.0,65238.0,22000.0,81975.0
2260667,16550,60 months,451.94,3 years,RENT,60000.0,Current,credit_card,18.40,0.0,1.0,NaN,NaN,13.0,0.0,25760,50.8,14.0,3008.99,4346.51,0.0,0.0,0.0,0.0,NaN,Individual,0.0,0.0,25760.0,2.0,0.0,0.0,0.0,NaN,0.0,NaN,3.0,8.0,6158.0,51.0,50700.0,0.0,0.0,2.0,8.0,1982.0,9816.0,49.7,0.0,0.0,NaN,41.0,3.0,3.0,0.0,10.0,NaN,0.0,NaN,0.0,5.0,12.0,5.0,5.0,0.0,13.0,14.0,12.0,13.0,0.0,0.0,0.0,3.0,100.0,20.0,0.0,0.0,50700.0,25760.0,19500.0,0.0

In [4]:
loans.groupby('loan_status')['loan_status'].count()

loan_status
Charged Off                                             255926
Current                                                 825914
Default                                                     24
Does not meet the credit policy. Status:Charged Off        761
Does not meet the credit policy. Status:Fully Paid        1988
Fully Paid                                             1024444
In Grace Period                                           7862
Late (16-30 days)                                         3323
Late (31-120 days)                                       19716
Name: loan_status, dtype: int64

In [5]:
#we'll only look at loans that are either charged off or fully paid
#change 'Does note meet...' to their shorter name
status_dict = {'Does not meet the credit policy. Status:Charged Off':'Charged Off',
           'Does not meet the credit policy. Status:Fully Paid':'Fully Paid'}

loans['loan_status'] = loans['loan_status'].replace(status_dict)

loans = loans[(loans['loan_status'] == 'Fully Paid') | (loans['loan_status'] == 'Charged Off')]

In [6]:
#check to make sure that the df is what we want
loans.groupby('loan_status')['loan_status'].count()

loan_status
Charged Off     256687
Fully Paid     1026432
Name: loan_status, dtype: int64

In [7]:
#create a dict to convert the employment lengths to ints
empl_dict = {'10+ years':10, 
             '6 years':6, 
             '4 years':4, 
             '< 1 year':0.5, 
             '2 years':2,
             '9 years':9, 
             '5 years':5, 
             '3 years':3, 
             '7 years':7, 
             '1 year':1,
             '8 years':8,
            np.nan:0}

loans['emp_length'] = loans['emp_length'].replace(empl_dict).astype(int, errors = 'ignore')

In [8]:
loans.groupby('emp_length')['emp_length'].count()

emp_length
0     172125
1      84944
2     116477
3     103038
4      77102
5      80711
6      60338
7      57608
8      58602
9      49030
10    423144
Name: emp_length, dtype: int64

In [9]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1283119 entries, 186 to 2260658
Data columns (total 81 columns):
 #   Column                          Non-Null Count    Dtype
---  ------                          --------------    -----
 0   loan_amnt                       1283119 non-null  int64
 1   term                            1283119 non-null  object
 2   installment                     1283119 non-null  float64
 3   emp_length                      1283119 non-null  int32
 4   home_ownership                  1283119 non-null  object
 5   annual_inc                      1283115 non-null  float64
 6   loan_status                     1283119 non-null  object
 7   purpose                         1283119 non-null  object
 8   dti                             1283119 non-null  float64
 9   delinq_2yrs                     1283090 non-null  float64
 10  inq_last_6mths                  1283089 non-null  float64
 11  mths_since_last_delinq          636119 non-null   float64
 12  mths_since_last_record          218361 non-null   float64
 13  open_acc                        1283090 non-null  float64
 14  pub_rec                         1283090 non-null  float64
 15  revol_bal                       1283119 non-null  int64
 16  revol_util                      1282303 non-null  float64
 17  total_acc                       1283090 non-null  float64
 18  total_rec_prncp                 1283119 non-null  float64
 19  total_rec_int                   1283119 non-null  float64
 20  total_rec_late_fee              1283119 non-null  float64
 21  recoveries                      1283119 non-null  float64
 22  collection_recovery_fee         1283119 non-null  float64
 23  collections_12_mths_ex_med      1282974 non-null  float64
 24  mths_since_last_major_derog     336801 non-null   float64
 25  application_type                1283119 non-null  object
 26  acc_now_delinq                  1283090 non-null  float64
 27  tot_coll_amt                    1212843 non-null  float64
 28  tot_cur_bal                     1212843 non-null  float64
 29  open_acc_6m                     476580 non-null   float64
 30  open_act_il                     476581 non-null   float64
 31  open_il_12m                     476581 non-null   float64
 32  open_il_24m                     476581 non-null   float64
 33  mths_since_rcnt_il              464253 non-null   float64
 34  total_bal_il                    476581 non-null   float64
 35  il_util                         413419 non-null   float64
 36  open_rv_12m                     476581 non-null   float64
 37  open_rv_24m                     476581 non-null   float64
 38  max_bal_bc                      476581 non-null   float64
 39  all_util                        476541 non-null   float64
 40  total_rev_hi_lim                1212843 non-null  float64
 41  inq_fi                          476581 non-null   float64
 42  total_cu_tl                     476580 non-null   float64
 43  inq_last_12m                    476580 non-null   float64
 44  acc_open_past_24mths            1233089 non-null  float64
 45  avg_cur_bal                     1212824 non-null  float64
 46  bc_open_to_buy                  1220263 non-null  float64
 47  bc_util                         1219530 non-null  float64
 48  chargeoff_within_12_mths        1282974 non-null  float64
 49  delinq_amnt                     1283090 non-null  float64
 50  mo_sin_old_il_acct              1176749 non-null  float64
 51  mo_sin_old_rev_tl_op            1212842 non-null  float64
 52  mo_sin_rcnt_rev_tl_op           1212842 non-null  float64
 53  mo_sin_rcnt_tl                  1212843 non-null  float64
 54  mort_acc                        1233089 non-null  float64
 55  mths_since_recent_bc            1221144 non-null  float64
 56  mths_since_recent_bc_dlq        304091 non-null   float64
 57  mths_since_recent_inq           1112994 non-null  float64
 58  mths_since_recent_revol_delinq  428463 non-null   float64
 59  num_accts_ever_120_pd           1212843 non-null  float64
 60  num_actv_bc_tl                  1212843 non-null  float64
 61  num_actv_rev_tl                 1212843 non-null  float64
 62  num_bc_sats                     1224529 non-null  float64
 63  num_bc_tl                       1212843 non-null  float64
 64  num_il_tl                       1212843 non-null  float64
 65  num_op_rev_tl                   1212843 non-null  float64
 66  num_rev_accts                   1212842 non-null  float64
 67  num_rev_tl_bal_gt_0             1212843 non-null  float64
 68  num_sats                        1224529 non-null  float64
 69  num_tl_120dpd_2m                1164801 non-null  float64
 70  num_tl_30dpd                    1212843 non-null  float64
 71  num_tl_90g_dpd_24m              1212843 non-null  float64
 72  num_tl_op_past_12m              1212843 non-null  float64
 73  pct_tl_nvr_dlq                  1212689 non-null  float64
 74  percent_bc_gt_75                1219855 non-null  float64
 75  pub_rec_bankruptcies            1281754 non-null  float64
 76  tax_liens                       1283014 non-null  float64
 77  tot_hi_cred_lim                 1212843 non-null  float64
 78  total_bal_ex_mort               1233089 non-null  float64
 79  total_bc_limit                  1233089 non-null  float64
 80  total_il_high_credit_limit      1212843 non-null  float64
dtypes: float64(73), int32(1), int64(2), object(5)
memory usage: 797.8+ MB

In [10]:
#it seems that a lot of the nans cross columns, so I will dropnas for open_rv_12m, and see 
#how that impacts the df
loans = loans[loans['open_rv_12m'].isna() == False]
loans.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 476581 entries, 186 to 2260658
Data columns (total 81 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   loan_amnt                       476581 non-null  int64
 1   term                            476581 non-null  object
 2   installment                     476581 non-null  float64
 3   emp_length                      476581 non-null  int32
 4   home_ownership                  476581 non-null  object
 5   annual_inc                      476581 non-null  float64
 6   loan_status                     476581 non-null  object
 7   purpose                         476581 non-null  object
 8   dti                             476581 non-null  float64
 9   delinq_2yrs                     476581 non-null  float64
 10  inq_last_6mths                  476580 non-null  float64
 11  mths_since_last_delinq          244109 non-null  float64
 12  mths_since_last_record          92928 non-null   float64
 13  open_acc                        476581 non-null  float64
 14  pub_rec                         476581 non-null  float64
 15  revol_bal                       476581 non-null  int64
 16  revol_util                      476235 non-null  float64
 17  total_acc                       476581 non-null  float64
 18  total_rec_prncp                 476581 non-null  float64
 19  total_rec_int                   476581 non-null  float64
 20  total_rec_late_fee              476581 non-null  float64
 21  recoveries                      476581 non-null  float64
 22  collection_recovery_fee         476581 non-null  float64
 23  collections_12_mths_ex_med      476581 non-null  float64
 24  mths_since_last_major_derog     136191 non-null  float64
 25  application_type                476581 non-null  object
 26  acc_now_delinq                  476581 non-null  float64
 27  tot_coll_amt                    476581 non-null  float64
 28  tot_cur_bal                     476581 non-null  float64
 29  open_acc_6m                     476580 non-null  float64
 30  open_act_il                     476581 non-null  float64
 31  open_il_12m                     476581 non-null  float64
 32  open_il_24m                     476581 non-null  float64
 33  mths_since_rcnt_il              464253 non-null  float64
 34  total_bal_il                    476581 non-null  float64
 35  il_util                         413419 non-null  float64
 36  open_rv_12m                     476581 non-null  float64
 37  open_rv_24m                     476581 non-null  float64
 38  max_bal_bc                      476581 non-null  float64
 39  all_util                        476541 non-null  float64
 40  total_rev_hi_lim                476581 non-null  float64
 41  inq_fi                          476581 non-null  float64
 42  total_cu_tl                     476580 non-null  float64
 43  inq_last_12m                    476580 non-null  float64
 44  acc_open_past_24mths            476581 non-null  float64
 45  avg_cur_bal                     476574 non-null  float64
 46  bc_open_to_buy                  471010 non-null  float64
 47  bc_util                         470746 non-null  float64
 48  chargeoff_within_12_mths        476581 non-null  float64
 49  delinq_amnt                     476581 non-null  float64
 50  mo_sin_old_il_acct              464253 non-null  float64
 51  mo_sin_old_rev_tl_op            476581 non-null  float64
 52  mo_sin_rcnt_rev_tl_op           476581 non-null  float64
 53  mo_sin_rcnt_tl                  476581 non-null  float64
 54  mort_acc                        476581 non-null  float64
 55  mths_since_recent_bc            471359 non-null  float64
 56  mths_since_recent_bc_dlq        116698 non-null  float64
 57  mths_since_recent_inq           433451 non-null  float64
 58  mths_since_recent_revol_delinq  166057 non-null  float64
 59  num_accts_ever_120_pd           476581 non-null  float64
 60  num_actv_bc_tl                  476581 non-null  float64
 61  num_actv_rev_tl                 476581 non-null  float64
 62  num_bc_sats                     476581 non-null  float64
 63  num_bc_tl                       476581 non-null  float64
 64  num_il_tl                       476581 non-null  float64
 65  num_op_rev_tl                   476581 non-null  float64
 66  num_rev_accts                   476581 non-null  float64
 67  num_rev_tl_bal_gt_0             476581 non-null  float64
 68  num_sats                        476581 non-null  float64
 69  num_tl_120dpd_2m                453159 non-null  float64
 70  num_tl_30dpd                    476581 non-null  float64
 71  num_tl_90g_dpd_24m              476581 non-null  float64
 72  num_tl_op_past_12m              476581 non-null  float64
 73  pct_tl_nvr_dlq                  476580 non-null  float64
 74  percent_bc_gt_75                470969 non-null  float64
 75  pub_rec_bankruptcies            476581 non-null  float64
 76  tax_liens                       476581 non-null  float64
 77  tot_hi_cred_lim                 476581 non-null  float64
 78  total_bal_ex_mort               476581 non-null  float64
 79  total_bc_limit                  476581 non-null  float64
 80  total_il_high_credit_limit      476581 non-null  float64
dtypes: float64(73), int32(1), int64(2), object(5)
memory usage: 296.3+ MB

The cell below is meant to expand the data set by filling in the nan vals with "assume the best" assumptions. I will run the model with all nans dropped, see how it fares, then add them back in with the imputed vals, and see if that improves the model.

In [11]:
#create lists of the columns that will employ different fillna methods
z_fill = ['percent_bc_gt_75']
mean_fill = ['collections_12_mths_ex_med', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m', 
             'open_act_il', 'open_il_12m', 'open_il_24m','total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
             'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths', 'avg_cur_bal', 
             'bc_open_to_buy', 'bc_util', 'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 
             'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_bc', 'num_rev_accts', 'num_tl_120dpd_2m',
             'annual_inc', 'delinq_2yrs', 'mths_since_last_delinq', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_util', 'total_acc',
             'mths_since_last_record', 'mths_since_last_major_derog', 'mths_since_rcnt_il',
             'mths_since_recent_bc_dlq', 'mths_since_recent_inq', 'mths_since_recent_revol_delinq']
hundred_fill = ['pct_tl_nvr_dlq']

#fill the columns based on the chosen method
for col in mean_fill:
    loans[col].fillna(loans[col].mean(), inplace = True)

loans[z_fill] = loans[z_fill].fillna(0)
loans[hundred_fill] = loans[hundred_fill].fillna(100)

In [12]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 476581 entries, 186 to 2260658
Data columns (total 81 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   loan_amnt                       476581 non-null  int64
 1   term                            476581 non-null  object
 2   installment                     476581 non-null  float64
 3   emp_length                      476581 non-null  int32
 4   home_ownership                  476581 non-null  object
 5   annual_inc                      476581 non-null  float64
 6   loan_status                     476581 non-null  object
 7   purpose                         476581 non-null  object
 8   dti                             476581 non-null  float64
 9   delinq_2yrs                     476581 non-null  float64
 10  inq_last_6mths                  476581 non-null  float64
 11  mths_since_last_delinq          476581 non-null  float64
 12  mths_since_last_record          476581 non-null  float64
 13  open_acc                        476581 non-null  float64
 14  pub_rec                         476581 non-null  float64
 15  revol_bal                       476581 non-null  int64
 16  revol_util                      476581 non-null  float64
 17  total_acc                       476581 non-null  float64
 18  total_rec_prncp                 476581 non-null  float64
 19  total_rec_int                   476581 non-null  float64
 20  total_rec_late_fee              476581 non-null  float64
 21  recoveries                      476581 non-null  float64
 22  collection_recovery_fee         476581 non-null  float64
 23  collections_12_mths_ex_med      476581 non-null  float64
 24  mths_since_last_major_derog     476581 non-null  float64
 25  application_type                476581 non-null  object
 26  acc_now_delinq                  476581 non-null  float64
 27  tot_coll_amt                    476581 non-null  float64
 28  tot_cur_bal                     476581 non-null  float64
 29  open_acc_6m                     476581 non-null  float64
 30  open_act_il                     476581 non-null  float64
 31  open_il_12m                     476581 non-null  float64
 32  open_il_24m                     476581 non-null  float64
 33  mths_since_rcnt_il              476581 non-null  float64
 34  total_bal_il                    476581 non-null  float64
 35  il_util                         476581 non-null  float64
 36  open_rv_12m                     476581 non-null  float64
 37  open_rv_24m                     476581 non-null  float64
 38  max_bal_bc                      476581 non-null  float64
 39  all_util                        476581 non-null  float64
 40  total_rev_hi_lim                476581 non-null  float64
 41  inq_fi                          476581 non-null  float64
 42  total_cu_tl                     476581 non-null  float64
 43  inq_last_12m                    476581 non-null  float64
 44  acc_open_past_24mths            476581 non-null  float64
 45  avg_cur_bal                     476581 non-null  float64
 46  bc_open_to_buy                  476581 non-null  float64
 47  bc_util                         476581 non-null  float64
 48  chargeoff_within_12_mths        476581 non-null  float64
 49  delinq_amnt                     476581 non-null  float64
 50  mo_sin_old_il_acct              476581 non-null  float64
 51  mo_sin_old_rev_tl_op            476581 non-null  float64
 52  mo_sin_rcnt_rev_tl_op           476581 non-null  float64
 53  mo_sin_rcnt_tl                  476581 non-null  float64
 54  mort_acc                        476581 non-null  float64
 55  mths_since_recent_bc            476581 non-null  float64
 56  mths_since_recent_bc_dlq        476581 non-null  float64
 57  mths_since_recent_inq           476581 non-null  float64
 58  mths_since_recent_revol_delinq  476581 non-null  float64
 59  num_accts_ever_120_pd           476581 non-null  float64
 60  num_actv_bc_tl                  476581 non-null  float64
 61  num_actv_rev_tl                 476581 non-null  float64
 62  num_bc_sats                     476581 non-null  float64
 63  num_bc_tl                       476581 non-null  float64
 64  num_il_tl                       476581 non-null  float64
 65  num_op_rev_tl                   476581 non-null  float64
 66  num_rev_accts                   476581 non-null  float64
 67  num_rev_tl_bal_gt_0             476581 non-null  float64
 68  num_sats                        476581 non-null  float64
 69  num_tl_120dpd_2m                476581 non-null  float64
 70  num_tl_30dpd                    476581 non-null  float64
 71  num_tl_90g_dpd_24m              476581 non-null  float64
 72  num_tl_op_past_12m              476581 non-null  float64
 73  pct_tl_nvr_dlq                  476581 non-null  float64
 74  percent_bc_gt_75                476581 non-null  float64
 75  pub_rec_bankruptcies            476581 non-null  float64
 76  tax_liens                       476581 non-null  float64
 77  tot_hi_cred_lim                 476581 non-null  float64
 78  total_bal_ex_mort               476581 non-null  float64
 79  total_bc_limit                  476581 non-null  float64
 80  total_il_high_credit_limit      476581 non-null  float64
dtypes: float64(73), int32(1), int64(2), object(5)
memory usage: 296.3+ MB

In [13]:
#look at the terms length uniques
loans.term.unique()

array([' 36 months', ' 60 months'], dtype=object)

In [14]:
#convert the term lengths to ints
term_dict = {' 36 months':36, ' 60 months':60}
loans.term = loans.term.replace(term_dict)
loans.term.unique()

array([36, 60], dtype=int64)

In [15]:
loans

,loan_amnt,term,installment,emp_length,home_ownership,annual_inc,loan_status,purpose,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,mths_since_last_major_derog,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
186,4500,36,147.99,10,RENT,38500.0,Fully Paid,credit_card,4.64,0.0,0.0,25.000000,70.103478,12.0,0.0,4472,15.3,25.0,4500.00,49.22,0.00,0.0,0.0,0.0,25.000000,Individual,0.0,306.0,29137.0,2.0,1.0,1.0,1.0,3.0,24665.0,100.00000,3.0,7.0,3612.0,54.0,29200.0,0.0,3.0,3.0,8.0,2428.0,10735.0,28.9,0.0,0.0,180.0,69.0,2.0,2.0,0.0,2.0,38.986264,6.000000,35.547149,1.0,3.0,5.0,5.0,6.0,10.0,11.0,15.0,5.0,12.0,0.0,0.0,0.0,4.0,91.7,0.0,0.0,0.0,53795.0,29137.0,15100.0,24595.0
269,20000,60,507.55,4,RENT,57000.0,Fully Paid,debt_consolidation,22.18,0.0,0.0,34.473436,70.103478,10.0,0.0,33356,45.9,16.0,20000.00,13.58,0.00,0.0,0.0,0.0,44.513771,Individual,0.0,0.0,33356.0,2.0,0.0,0.0,0.0,78.0,0.0,71.53946,2.0,3.0,18416.0,46.0,72700.0,0.0,0.0,0.0,3.0,3336.0,32170.0,50.4,0.0,0.0,78.0,284.0,5.0,5.0,1.0,27.0,38.986264,17.000000,35.547149,0.0,4.0,7.0,6.0,9.0,1.0,10.0,14.0,7.0,10.0,0.0,0.0,0.0,2.0,100.0,33.3,0.0,0.0,72700.0,33356.0,64800.0,0.0
271,6600,36,217.05,10,RENT,45000.0,Fully Paid,credit_card,16.21,0.0,0.0,34.473436,70.103478,6.0,0.0,6167,58.2,13.0,6600.00,22.81,0.00,0.0,0.0,0.0,44.513771,Individual,0.0,0.0,26836.0,0.0,2.0,0.0,0.0,27.0,20669.0,74.00000,0.0,2.0,3356.0,70.0,10600.0,0.0,1.0,0.0,2.0,4473.0,4433.0,58.2,0.0,0.0,116.0,108.0,18.0,18.0,0.0,18.0,38.986264,6.516169,35.547149,0.0,2.0,2.0,4.0,4.0,5.0,4.0,8.0,2.0,6.0,0.0,0.0,0.0,0.0,84.6,50.0,0.0,0.0,38607.0,26836.0,10600.0,28007.0
296,2500,36,84.92,5,RENT,42000.0,Fully Paid,other,15.09,0.0,0.0,53.000000,70.103478,3.0,0.0,3319,31.6,6.0,2500.00,1.29,0.00,0.0,0.0,0.0,44.513771,Individual,0.0,0.0,18649.0,1.0,1.0,0.0,1.0,22.0,15330.0,69.00000,1.0,2.0,2792.0,57.0,10500.0,2.0,0.0,1.0,3.0,6216.0,7181.0,31.6,0.0,0.0,177.0,177.0,5.0,5.0,0.0,5.0,38.986264,12.000000,35.547149,0.0,2.0,2.0,2.0,2.0,3.0,2.0,3.0,2.0,3.0,0.0,0.0,0.0,1.0,83.3,0.0,0.0,0.0,32582.0,18649.0,10500.0,22082.0
369,4000,36,144.55,5,MORTGAGE,60000.0,Fully Paid,house,19.10,0.0,1.0,38.000000,70.103478,11.0,0.0,382,7.3,18.0,4000.00,49.92,0.00,0.0,0.0,0.0,38.000000,Individual,0.0,0.0,106556.0,2.0,3.0,3.0,4.0,1.0,45868.0,77.00000,1.0,6.0,378.0,72.0,5200.0,3.0,0.0,3.0,10.0,9687.0,3818.0,9.1,0.0,0.0,57.0,31.0,12.0,1.0,2.0,15.0,38.986264,2.000000,35.547149,1.0,2.0,2.0,5.0,5.0,9.0,7.0,7.0,2.0,11.0,0.0,0.0,0.0,4.0,88.2,0.0,0.0,0.0,127200.0,46250.0,4200.0,59474.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260652,25000,60,818.85,0,RENT,54778.0,Fully Paid,debt_consolidation,12.81,1.0,0.0,4.000000,70.103478,14.0,0.0,4521,11.6,27.0,25000.00,27.67,0.00,0.0,0.0,0.0,50.000000,Individual,0.0,0.0,25299.0,2.0,1.0,2.0,2.0,6.0,20422.0,95.00000,4.0,6.0,1896.0,40.0,42700.0,0.0,3.0,2.0,9.0,1807.0,33679.0,13.1,0.0,247.0,120.0,352.0,6.0,6.0,0.0,6.0,50.000000,12.000000,50.000000,3.0,5.0,5.0,7.0,14.0,6.0,10.0,19.0,5.0,13.0,0.0,0.0,0.0,6.0,88.0,0.0,0.0,0.0,66614.0,25299.0,38200.0,21532.0
2260654,30000,60,747.03,2,RENT,80000.0,Charged Off,debt_consolidation,23.22,0.0,1.0,46.000000,70.103478,21.0,0.0,19224,30.8,69.0,2689.46,3358.00,0.00,0.0,0.0,0.0,61.000000,Individual,0.0,0.0,196622.0,2.0,9.0,1.0,1.0,8.0,177398.0,101.00000,2.0,3.0,11301.0,61.0,62400.0,0.0,0.0,1.0,4.0,9831.0,31294.0,36.5,0.0,0.0,189.0,171.0,5.0,5.0,0.0,5.0,38.986264,2.000000,46.000000,22.0,5.0,6.0,6.0,8.0,51.0,12.0,18.0,6.0,21.0,0.0,0.0,0.0,3.0,54.9,33.3,0.0,0.0,231009.0,196622.0,49300.0,168609.0
2260655,18000,60,589.57,10,MORTGAGE,77000.0,Charged Off,debt_consolidation,8.08,0.0,1.0,38.000000,70.103478,9.0,0.0,10100,45.1,15.0,1110.53,4164.95,117.92,0.0,0.0,0.0,44.513771,Individual,0.0,265.0,324621.0,5.0,1.0,1.0,1.0,4.0,6925.0,98.00000,3.0,3.0,3358.0,59.0,22400.0,0.0,3.0,7.0,6.0,36069.0,7083.0,48.7,0.0,0.0,156.0,52.0,4.0,4.0,1.0,5.0,38.000000,4.000000,38.000000,0.0,3.0,5.0,4.0,4.0,7.0,6.0,6.0,5.0,9.0,0.0,0.0,0.0,5.0,93.3,50.0,0.0,0.0,338546.0,18113.0,13800.0,7058.0
2260656,17950,60,582.62,10,MORTGAGE,53758.0,Fully Paid,debt_consolidation,33.24,0.0,1.0,34.473436,80.000000,11.0,1.0,5959,35.9,24.0,17950.00,2853.78,0.00,0.0,0.0,0.0,44.513771,Individual,0.0,0.0,156247.0,0.0,3.0,1.0,1.0,11.0,30693.0,49.00000,1.0,4.0,2413.0,46.0,16600.0,1.0,1.0,2.0,5.0,15625.0,1587.0,60.3,0.0,0.0,109.0,201.0,11.0,11.0,3.0,16.0,38.986264,0.000000,35.547149,0.0,1.0,5.0,1.0,4.0,7.0,7.0,14.0,5.0,11.0,0.0,0.0,0.0,2.0,100.0,0.0,1.0,0.0,203667.0,36652.0,4000.0,63002.0
2260658,15000,60,364.94,0,RENT,85000.0,Fully Paid,debt_consolidation,14.66,0.0,3.0,36.000000,70.103478,19.0,0.0,6988,24.8,87.0,15000.00,1112.32,0.00,0.0,0.0,0.0,36.000000,Individual,0.0,4199.0,239081.0,5.0,5.0,3.0,7.0,4.0,232093.0,70.00000,4.0,10.0,2534.0,52.0,28200.0,1.0,2.0,7.0,17.0,17077.0,17477.0,23.7,0.0,0.0,191.0,198.0,0.0,0.0,1.0,2.0,36.000000,0.000000,36.000000,7.0,4.0,6.0,8.0,17.0,55.0,13.0,31.0,6.0,19.0,0.0,0.0,0.0,7.0,89.0,0.0,0.0,0.0,267274.0,239081.0,22900.0,239074.0

In [16]:
#create a target value: portion_repayed
loans['portion_repayed'] = loans['total_rec_prncp'] / loans['loan_amnt']

In [17]:
#check to make sure that the percent recovered vals make sense
loans.groupby('loan_status')['portion_repayed'].mean()

loan_status
Charged Off    0.240134
Fully Paid     1.000000
Name: portion_repayed, dtype: float64

In [18]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 476581 entries, 186 to 2260658
Data columns (total 82 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   loan_amnt                       476581 non-null  int64
 1   term                            476581 non-null  int64
 2   installment                     476581 non-null  float64
 3   emp_length                      476581 non-null  int32
 4   home_ownership                  476581 non-null  object
 5   annual_inc                      476581 non-null  float64
 6   loan_status                     476581 non-null  object
 7   purpose                         476581 non-null  object
 8   dti                             476581 non-null  float64
 9   delinq_2yrs                     476581 non-null  float64
 10  inq_last_6mths                  476581 non-null  float64
 11  mths_since_last_delinq          476581 non-null  float64
 12  mths_since_last_record          476581 non-null  float64
 13  open_acc                        476581 non-null  float64
 14  pub_rec                         476581 non-null  float64
 15  revol_bal                       476581 non-null  int64
 16  revol_util                      476581 non-null  float64
 17  total_acc                       476581 non-null  float64
 18  total_rec_prncp                 476581 non-null  float64
 19  total_rec_int                   476581 non-null  float64
 20  total_rec_late_fee              476581 non-null  float64
 21  recoveries                      476581 non-null  float64
 22  collection_recovery_fee         476581 non-null  float64
 23  collections_12_mths_ex_med      476581 non-null  float64
 24  mths_since_last_major_derog     476581 non-null  float64
 25  application_type                476581 non-null  object
 26  acc_now_delinq                  476581 non-null  float64
 27  tot_coll_amt                    476581 non-null  float64
 28  tot_cur_bal                     476581 non-null  float64
 29  open_acc_6m                     476581 non-null  float64
 30  open_act_il                     476581 non-null  float64
 31  open_il_12m                     476581 non-null  float64
 32  open_il_24m                     476581 non-null  float64
 33  mths_since_rcnt_il              476581 non-null  float64
 34  total_bal_il                    476581 non-null  float64
 35  il_util                         476581 non-null  float64
 36  open_rv_12m                     476581 non-null  float64
 37  open_rv_24m                     476581 non-null  float64
 38  max_bal_bc                      476581 non-null  float64
 39  all_util                        476581 non-null  float64
 40  total_rev_hi_lim                476581 non-null  float64
 41  inq_fi                          476581 non-null  float64
 42  total_cu_tl                     476581 non-null  float64
 43  inq_last_12m                    476581 non-null  float64
 44  acc_open_past_24mths            476581 non-null  float64
 45  avg_cur_bal                     476581 non-null  float64
 46  bc_open_to_buy                  476581 non-null  float64
 47  bc_util                         476581 non-null  float64
 48  chargeoff_within_12_mths        476581 non-null  float64
 49  delinq_amnt                     476581 non-null  float64
 50  mo_sin_old_il_acct              476581 non-null  float64
 51  mo_sin_old_rev_tl_op            476581 non-null  float64
 52  mo_sin_rcnt_rev_tl_op           476581 non-null  float64
 53  mo_sin_rcnt_tl                  476581 non-null  float64
 54  mort_acc                        476581 non-null  float64
 55  mths_since_recent_bc            476581 non-null  float64
 56  mths_since_recent_bc_dlq        476581 non-null  float64
 57  mths_since_recent_inq           476581 non-null  float64
 58  mths_since_recent_revol_delinq  476581 non-null  float64
 59  num_accts_ever_120_pd           476581 non-null  float64
 60  num_actv_bc_tl                  476581 non-null  float64
 61  num_actv_rev_tl                 476581 non-null  float64
 62  num_bc_sats                     476581 non-null  float64
 63  num_bc_tl                       476581 non-null  float64
 64  num_il_tl                       476581 non-null  float64
 65  num_op_rev_tl                   476581 non-null  float64
 66  num_rev_accts                   476581 non-null  float64
 67  num_rev_tl_bal_gt_0             476581 non-null  float64
 68  num_sats                        476581 non-null  float64
 69  num_tl_120dpd_2m                476581 non-null  float64
 70  num_tl_30dpd                    476581 non-null  float64
 71  num_tl_90g_dpd_24m              476581 non-null  float64
 72  num_tl_op_past_12m              476581 non-null  float64
 73  pct_tl_nvr_dlq                  476581 non-null  float64
 74  percent_bc_gt_75                476581 non-null  float64
 75  pub_rec_bankruptcies            476581 non-null  float64
 76  tax_liens                       476581 non-null  float64
 77  tot_hi_cred_lim                 476581 non-null  float64
 78  total_bal_ex_mort               476581 non-null  float64
 79  total_bc_limit                  476581 non-null  float64
 80  total_il_high_credit_limit      476581 non-null  float64
 81  portion_repayed                 476581 non-null  float64
dtypes: float64(74), int32(1), int64(3), object(4)
memory usage: 300.0+ MB

In [19]:
#convert home_ownership, verification_status, purpose, application_type to categoricals
cats =['home_ownership', 'purpose', 'application_type', 'loan_status']
loans[cats] = loans[cats].astype('category')
loans[cats].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 476581 entries, 186 to 2260658
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   home_ownership    476581 non-null  category
 1   purpose           476581 non-null  category
 2   application_type  476581 non-null  category
 3   loan_status       476581 non-null  category
dtypes: category(4)
memory usage: 5.5 MB

In [20]:
#convert home_ownership, verification_status, purpose, application_type to one-hot encoded dummies
loans_dummies = pd.get_dummies(loans, columns = ['home_ownership', 'purpose', 'application_type'])

In [21]:
#drop application type
loans_dummies = loans_dummies.drop(['application_type_Individual'], axis = 1)

In [22]:
display(loans_dummies)

,loan_amnt,term,installment,emp_length,annual_inc,loan_status,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,mths_since_last_major_derog,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,portion_repayed,home_ownership_ANY,home_ownership_MORTGAGE,home_ownership_NONE,home_ownership_OWN,home_ownership_RENT,purpose_car,purpose_credit_card,purpose_debt_consolidation,purpose_home_improvement,purpose_house,purpose_major_purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding
186,4500,36,147.99,10,38500.0,Fully Paid,4.64,0.0,0.0,25.000000,70.103478,12.0,0.0,4472,15.3,25.0,4500.00,49.22,0.00,0.0,0.0,0.0,25.000000,0.0,306.0,29137.0,2.0,1.0,1.0,1.0,3.0,24665.0,100.00000,3.0,7.0,3612.0,54.0,29200.0,0.0,3.0,3.0,8.0,2428.0,10735.0,28.9,0.0,0.0,180.0,69.0,2.0,2.0,0.0,2.0,38.986264,6.000000,35.547149,1.0,3.0,5.0,5.0,6.0,10.0,11.0,15.0,5.0,12.0,0.0,0.0,0.0,4.0,91.7,0.0,0.0,0.0,53795.0,29137.0,15100.0,24595.0,1.000000,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0
269,20000,60,507.55,4,57000.0,Fully Paid,22.18,0.0,0.0,34.473436,70.103478,10.0,0.0,33356,45.9,16.0,20000.00,13.58,0.00,0.0,0.0,0.0,44.513771,0.0,0.0,33356.0,2.0,0.0,0.0,0.0,78.0,0.0,71.53946,2.0,3.0,18416.0,46.0,72700.0,0.0,0.0,0.0,3.0,3336.0,32170.0,50.4,0.0,0.0,78.0,284.0,5.0,5.0,1.0,27.0,38.986264,17.000000,35.547149,0.0,4.0,7.0,6.0,9.0,1.0,10.0,14.0,7.0,10.0,0.0,0.0,0.0,2.0,100.0,33.3,0.0,0.0,72700.0,33356.0,64800.0,0.0,1.000000,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
271,6600,36,217.05,10,45000.0,Fully Paid,16.21,0.0,0.0,34.473436,70.103478,6.0,0.0,6167,58.2,13.0,6600.00,22.81,0.00,0.0,0.0,0.0,44.513771,0.0,0.0,26836.0,0.0,2.0,0.0,0.0,27.0,20669.0,74.00000,0.0,2.0,3356.0,70.0,10600.0,0.0,1.0,0.0,2.0,4473.0,4433.0,58.2,0.0,0.0,116.0,108.0,18.0,18.0,0.0,18.0,38.986264,6.516169,35.547149,0.0,2.0,2.0,4.0,4.0,5.0,4.0,8.0,2.0,6.0,0.0,0.0,0.0,0.0,84.6,50.0,0.0,0.0,38607.0,26836.0,10600.0,28007.0,1.000000,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0
296,2500,36,84.92,5,42000.0,Fully Paid,15.09,0.0,0.0,53.000000,70.103478,3.0,0.0,3319,31.6,6.0,2500.00,1.29,0.00,0.0,0.0,0.0,44.513771,0.0,0.0,18649.0,1.0,1.0,0.0,1.0,22.0,15330.0,69.00000,1.0,2.0,2792.0,57.0,10500.0,2.0,0.0,1.0,3.0,6216.0,7181.0,31.6,0.0,0.0,177.0,177.0,5.0,5.0,0.0,5.0,38.986264,12.000000,35.547149,0.0,2.0,2.0,2.0,2.0,3.0,2.0,3.0,2.0,3.0,0.0,0.0,0.0,1.0,83.3,0.0,0.0,0.0,32582.0,18649.0,10500.0,22082.0,1.000000,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
369,4000,36,144.55,5,60000.0,Fully Paid,19.10,0.0,1.0,38.000000,70.103478,11.0,0.0,382,7.3,18.0,4000.00,49.92,0.00,0.0,0.0,0.0,38.000000,0.0,0.0,106556.0,2.0,3.0,3.0,4.0,1.0,45868.0,77.00000,1.0,6.0,378.0,72.0,5200.0,3.0,0.0,3.0,10.0,9687.0,3818.0,9.1,0.0,0.0,57.0,31.0,12.0,1.0,2.0,15.0,38.986264,2.000000,35.547149,1.0,2.0,2.0,5.0,5.0,9.0,7.0,7.0,2.0,11.0,0.0,0.0,0.0,4.0,88.2,0.0,0.0,0.0,127200.0,46250.0,4200.0,59474.0,1.000000,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260652,25000,60,818.85,0,54778.0,Fully Paid,12.81,1.0,0.0,4.000000,70.103478,14.0,0.0,4521,11.6,27.0,25000.00,27.67,0.00,0.0,0.0,0.0,50.000000,0.0,0.0,25299.0,2.0,1.0,2.0,2.0,6.0,20422.0,95.00000,4.0,6.0,1896.0,40.0,42700.0,0.0,3.0,2.0,9.0,1807.0,33679.0,13.1,0.0,247.0,120.0,352.0,6.0,6.0,0.0,6.0,50.000000,12.000000,50.000000,3.0,5.0,5.0,7.0,14.0,6.0,10.0,19.0,5.0,13.0,0.0,0.0,0.0,6.0,88.0,0.0,0.0,0.0,66614.0,25299.0,38200.0,21532.0,1.000000,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
2260654,30000,60,747.03,2,80000.0,Charged Off,23.22,0.0,1.0,46.000000,70.103478,21.0,0.0,19224,30.8,69.0,2689.46,3358.00,0.00,0.0,0.0,0.0,61.000000,0.0,0.0,196622.0,2.0,9.0,1.0,1.0,8.0,177398.0,101.00000,2.0,3.0,11301.0,61.0,62400.0,0.0,0.0,1.0,4.0,9831.0,31294.0,36.5,0.0,0.0,189.0,171.0,5.0,5.0,0.0,5.0,38.986264,2.000000,46.000000,22.0,5.0,6.0,6.0,8.0,51.0,12.0,18.0,6.0,21.0,0.0,0.0,0.0,3.0,54.9,33.3,0.0,0.0,231009.0,196622.0,49300.0,168609.0,0.089649,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
2260655,18000,60,589.57,10,77000.0,Charged Off,8.08,0.0,1.0,38.000000,70.103478,9.0,0.0,10100,45.1,15.0,1110.53,4164.95,117.92,0.0,0.0,0.0,44.513771,0.0,265.0,324621.0,5.0,1.0,1.0,1.0,4.0,6925.0,98.00000,3.0,3.0,3358.0,59.0,22400.0,0.0,3.0,7.0,6.0,36069.0,7083.0,48.7,0.0,0.0,156.0,52.0,4.0,4.0,1.0,5.0,38.000000,4.000000,38.000000,0.0,3.0,5.0,4.0,4.0,7.0,6.0,6.0,5.0,9.0,0.0,0.0,0.0,5.0,93.3,50.0,0.0,0.0,338546.0,18113.0,13800.0,7058.0,0.061696,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2260656,17950,60,582.62,10,53758.0,Fully Paid,33.24,0.0,1.0,34.473436,80.000000,11.0,1.0,5959,35.9,24.0,17950.00,2853.78,0.00,0.0,0.0,0.0,44.513771,0.0,0.0,156247.0,0.0,3.0,1.0,1.0,11.0,30693.0,49.00000,1.0,4.0,2413.0,46.0,16600.0,1.0,1.0,2.0,5.0,15625.0,1587.0,60.3,0.0,0.0,109.0,201.0,11.0,11.0,3.0,16.0,38.986264,0.000000,35.547149,0.0,1.0,5.0,1.0,4.0,7.0,7.0,14.0,5.0,11.0,0.0,0.0,0.0,2.0,100.0,0.0,1.0,0.0,203667.0,36652.0,4000.0,63002.0,1.000000,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2260658,15000,60,364.94,0,85000.0,Fully Paid,14.66,0.0,3.0,36.000000,70.103478,19.0,0.0,6988,24.8,87.0,15000.00,1112.32,0.00,0.0,0.0,0.0,36.000000,0.0,4199.0,239081.0,5.0,5.0,3.0,7.0,4.0,232093.0,70.00000,4.0,10.0,2534.0,52.0,28200.0,1.0,2.0,7.0,17.0,17077.0,17477.0,23.7,0.0,0.0,191.0,198.0,0.0,0.0,1.0,2.0,36.000000,0.000000,36.000000,7.0,4.0,6.0,8.0,17.0,55.0,13.0,31.0,6.0,19.0,0.0,0.0,0.0,7.0,89.0,0.0,0.0,0.0,267274.0,239081.0,22900.0,239074.0,1.000000,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0

In [23]:
loans_dummies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 476581 entries, 186 to 2260658
Data columns (total 97 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   loan_amnt                       476581 non-null  int64
 1   term                            476581 non-null  int64
 2   installment                     476581 non-null  float64
 3   emp_length                      476581 non-null  int32
 4   annual_inc                      476581 non-null  float64
 5   loan_status                     476581 non-null  category
 6   dti                             476581 non-null  float64
 7   delinq_2yrs                     476581 non-null  float64
 8   inq_last_6mths                  476581 non-null  float64
 9   mths_since_last_delinq          476581 non-null  float64
 10  mths_since_last_record          476581 non-null  float64
 11  open_acc                        476581 non-null  float64
 12  pub_rec                         476581 non-null  float64
 13  revol_bal                       476581 non-null  int64
 14  revol_util                      476581 non-null  float64
 15  total_acc                       476581 non-null  float64
 16  total_rec_prncp                 476581 non-null  float64
 17  total_rec_int                   476581 non-null  float64
 18  total_rec_late_fee              476581 non-null  float64
 19  recoveries                      476581 non-null  float64
 20  collection_recovery_fee         476581 non-null  float64
 21  collections_12_mths_ex_med      476581 non-null  float64
 22  mths_since_last_major_derog     476581 non-null  float64
 23  acc_now_delinq                  476581 non-null  float64
 24  tot_coll_amt                    476581 non-null  float64
 25  tot_cur_bal                     476581 non-null  float64
 26  open_acc_6m                     476581 non-null  float64
 27  open_act_il                     476581 non-null  float64
 28  open_il_12m                     476581 non-null  float64
 29  open_il_24m                     476581 non-null  float64
 30  mths_since_rcnt_il              476581 non-null  float64
 31  total_bal_il                    476581 non-null  float64
 32  il_util                         476581 non-null  float64
 33  open_rv_12m                     476581 non-null  float64
 34  open_rv_24m                     476581 non-null  float64
 35  max_bal_bc                      476581 non-null  float64
 36  all_util                        476581 non-null  float64
 37  total_rev_hi_lim                476581 non-null  float64
 38  inq_fi                          476581 non-null  float64
 39  total_cu_tl                     476581 non-null  float64
 40  inq_last_12m                    476581 non-null  float64
 41  acc_open_past_24mths            476581 non-null  float64
 42  avg_cur_bal                     476581 non-null  float64
 43  bc_open_to_buy                  476581 non-null  float64
 44  bc_util                         476581 non-null  float64
 45  chargeoff_within_12_mths        476581 non-null  float64
 46  delinq_amnt                     476581 non-null  float64
 47  mo_sin_old_il_acct              476581 non-null  float64
 48  mo_sin_old_rev_tl_op            476581 non-null  float64
 49  mo_sin_rcnt_rev_tl_op           476581 non-null  float64
 50  mo_sin_rcnt_tl                  476581 non-null  float64
 51  mort_acc                        476581 non-null  float64
 52  mths_since_recent_bc            476581 non-null  float64
 53  mths_since_recent_bc_dlq        476581 non-null  float64
 54  mths_since_recent_inq           476581 non-null  float64
 55  mths_since_recent_revol_delinq  476581 non-null  float64
 56  num_accts_ever_120_pd           476581 non-null  float64
 57  num_actv_bc_tl                  476581 non-null  float64
 58  num_actv_rev_tl                 476581 non-null  float64
 59  num_bc_sats                     476581 non-null  float64
 60  num_bc_tl                       476581 non-null  float64
 61  num_il_tl                       476581 non-null  float64
 62  num_op_rev_tl                   476581 non-null  float64
 63  num_rev_accts                   476581 non-null  float64
 64  num_rev_tl_bal_gt_0             476581 non-null  float64
 65  num_sats                        476581 non-null  float64
 66  num_tl_120dpd_2m                476581 non-null  float64
 67  num_tl_30dpd                    476581 non-null  float64
 68  num_tl_90g_dpd_24m              476581 non-null  float64
 69  num_tl_op_past_12m              476581 non-null  float64
 70  pct_tl_nvr_dlq                  476581 non-null  float64
 71  percent_bc_gt_75                476581 non-null  float64
 72  pub_rec_bankruptcies            476581 non-null  float64
 73  tax_liens                       476581 non-null  float64
 74  tot_hi_cred_lim                 476581 non-null  float64
 75  total_bal_ex_mort               476581 non-null  float64
 76  total_bc_limit                  476581 non-null  float64
 77  total_il_high_credit_limit      476581 non-null  float64
 78  portion_repayed                 476581 non-null  float64
 79  home_ownership_ANY              476581 non-null  uint8
 80  home_ownership_MORTGAGE         476581 non-null  uint8
 81  home_ownership_NONE             476581 non-null  uint8
 82  home_ownership_OWN              476581 non-null  uint8
 83  home_ownership_RENT             476581 non-null  uint8
 84  purpose_car                     476581 non-null  uint8
 85  purpose_credit_card             476581 non-null  uint8
 86  purpose_debt_consolidation      476581 non-null  uint8
 87  purpose_home_improvement        476581 non-null  uint8
 88  purpose_house                   476581 non-null  uint8
 89  purpose_major_purchase          476581 non-null  uint8
 90  purpose_medical                 476581 non-null  uint8
 91  purpose_moving                  476581 non-null  uint8
 92  purpose_other                   476581 non-null  uint8
 93  purpose_renewable_energy        476581 non-null  uint8
 94  purpose_small_business          476581 non-null  uint8
 95  purpose_vacation                476581 non-null  uint8
 96  purpose_wedding                 476581 non-null  uint8
dtypes: category(1), float64(74), int32(1), int64(3), uint8(18)
memory usage: 294.1 MB

In [24]:
#drop remaining nans
loans_dummies = loans_dummies.dropna()

In [25]:
#drop the variables that act as proxies for repayment
loans = loans_dummies.drop(['total_rec_prncp', 
                    'total_rec_int', 
                    'total_rec_late_fee', 
                    'recoveries', 
                    'collection_recovery_fee',
                    'installment',
                    'portion_repayed'], axis = 1)

In [36]:
#create a boolean column to represent whether or not the loan was repayed
loans['repayed']=loans['loan_status']=='Fully Paid'
loans.drop('loan_status', axis=1, inplace = True)
loans

,loan_amnt,term,emp_length,annual_inc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,collections_12_mths_ex_med,mths_since_last_major_derog,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,home_ownership_ANY,home_ownership_MORTGAGE,home_ownership_NONE,home_ownership_OWN,home_ownership_RENT,purpose_car,purpose_credit_card,purpose_debt_consolidation,purpose_home_improvement,purpose_house,purpose_major_purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding,repayed
186,4500,36,10,38500.0,4.64,0.0,0.0,25.000000,70.103478,12.0,0.0,4472,15.3,25.0,0.0,25.000000,0.0,306.0,29137.0,2.0,1.0,1.0,1.0,3.0,24665.0,100.00000,3.0,7.0,3612.0,54.0,29200.0,0.0,3.0,3.0,8.0,2428.0,10735.0,28.9,0.0,0.0,180.0,69.0,2.0,2.0,0.0,2.0,38.986264,6.000000,35.547149,1.0,3.0,5.0,5.0,6.0,10.0,11.0,15.0,5.0,12.0,0.0,0.0,0.0,4.0,91.7,0.0,0.0,0.0,53795.0,29137.0,15100.0,24595.0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,True
269,20000,60,4,57000.0,22.18,0.0,0.0,34.473436,70.103478,10.0,0.0,33356,45.9,16.0,0.0,44.513771,0.0,0.0,33356.0,2.0,0.0,0.0,0.0,78.0,0.0,71.53946,2.0,3.0,18416.0,46.0,72700.0,0.0,0.0,0.0,3.0,3336.0,32170.0,50.4,0.0,0.0,78.0,284.0,5.0,5.0,1.0,27.0,38.986264,17.000000,35.547149,0.0,4.0,7.0,6.0,9.0,1.0,10.0,14.0,7.0,10.0,0.0,0.0,0.0,2.0,100.0,33.3,0.0,0.0,72700.0,33356.0,64800.0,0.0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,True
271,6600,36,10,45000.0,16.21,0.0,0.0,34.473436,70.103478,6.0,0.0,6167,58.2,13.0,0.0,44.513771,0.0,0.0,26836.0,0.0,2.0,0.0,0.0,27.0,20669.0,74.00000,0.0,2.0,3356.0,70.0,10600.0,0.0,1.0,0.0,2.0,4473.0,4433.0,58.2,0.0,0.0,116.0,108.0,18.0,18.0,0.0,18.0,38.986264,6.516169,35.547149,0.0,2.0,2.0,4.0,4.0,5.0,4.0,8.0,2.0,6.0,0.0,0.0,0.0,0.0,84.6,50.0,0.0,0.0,38607.0,26836.0,10600.0,28007.0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,True
296,2500,36,5,42000.0,15.09,0.0,0.0,53.000000,70.103478,3.0,0.0,3319,31.6,6.0,0.0,44.513771,0.0,0.0,18649.0,1.0,1.0,0.0,1.0,22.0,15330.0,69.00000,1.0,2.0,2792.0,57.0,10500.0,2.0,0.0,1.0,3.0,6216.0,7181.0,31.6,0.0,0.0,177.0,177.0,5.0,5.0,0.0,5.0,38.986264,12.000000,35.547149,0.0,2.0,2.0,2.0,2.0,3.0,2.0,3.0,2.0,3.0,0.0,0.0,0.0,1.0,83.3,0.0,0.0,0.0,32582.0,18649.0,10500.0,22082.0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,True
369,4000,36,5,60000.0,19.10,0.0,1.0,38.000000,70.103478,11.0,0.0,382,7.3,18.0,0.0,38.000000,0.0,0.0,106556.0,2.0,3.0,3.0,4.0,1.0,45868.0,77.00000,1.0,6.0,378.0,72.0,5200.0,3.0,0.0,3.0,10.0,9687.0,3818.0,9.1,0.0,0.0,57.0,31.0,12.0,1.0,2.0,15.0,38.986264,2.000000,35.547149,1.0,2.0,2.0,5.0,5.0,9.0,7.0,7.0,2.0,11.0,0.0,0.0,0.0,4.0,88.2,0.0,0.0,0.0,127200.0,46250.0,4200.0,59474.0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260652,25000,60,0,54778.0,12.81,1.0,0.0,4.000000,70.103478,14.0,0.0,4521,11.6,27.0,0.0,50.000000,0.0,0.0,25299.0,2.0,1.0,2.0,2.0,6.0,20422.0,95.00000,4.0,6.0,1896.0,40.0,42700.0,0.0,3.0,2.0,9.0,1807.0,33679.0,13.1,0.0,247.0,120.0,352.0,6.0,6.0,0.0,6.0,50.000000,12.000000,50.000000,3.0,5.0,5.0,7.0,14.0,6.0,10.0,19.0,5.0,13.0,0.0,0.0,0.0,6.0,88.0,0.0,0.0,0.0,66614.0,25299.0,38200.0,21532.0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,True
2260654,30000,60,2,80000.0,23.22,0.0,1.0,46.000000,70.103478,21.0,0.0,19224,30.8,69.0,0.0,61.000000,0.0,0.0,196622.0,2.0,9.0,1.0,1.0,8.0,177398.0,101.00000,2.0,3.0,11301.0,61.0,62400.0,0.0,0.0,1.0,4.0,9831.0,31294.0,36.5,0.0,0.0,189.0,171.0,5.0,5.0,0.0,5.0,38.986264,2.000000,46.000000,22.0,5.0,6.0,6.0,8.0,51.0,12.0,18.0,6.0,21.0,0.0,0.0,0.0,3.0,54.9,33.3,0.0,0.0,231009.0,196622.0,49300.0,168609.0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,False
2260655,18000,60,10,77000.0,8.08,0.0,1.0,38.000000,70.103478,9.0,0.0,10100,45.1,15.0,0.0,44.513771,0.0,265.0,324621.0,5.0,1.0,1.0,1.0,4.0,6925.0,98.00000,3.0,3.0,3358.0,59.0,22400.0,0.0,3.0,7.0,6.0,36069.0,7083.0,48.7,0.0,0.0,156.0,52.0,4.0,4.0,1.0,5.0,38.000000,4.000000,38.000000,0.0,3.0,5.0,4.0,4.0,7.0,6.0,6.0,5.0,9.0,0.0,0.0,0.0,5.0,93.3,50.0,0.0,0.0,338546.0,18113.0,13800.0,7058.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,False
2260656,17950,60,10,53758.0,33.24,0.0,1.0,34.473436,80.000000,11.0,1.0,5959,35.9,24.0,0.0,44.513771,0.0,0.0,156247.0,0.0,3.0,1.0,1.0,11.0,30693.0,49.00000,1.0,4.0,2413.0,46.0,16600.0,1.0,1.0,2.0,5.0,15625.0,1587.0,60.3,0.0,0.0,109.0,201.0,11.0,11.0,3.0,16.0,38.986264,0.000000,35.547149,0.0,1.0,5.0,1.0,4.0,7.0,7.0,14.0,5.0,11.0,0.0,0.0,0.0,2.0,100.0,0.0,1.0,0.0,203667.0,36652.0,4000.0,63002.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,True
2260658,15000,60,0,85000.0,14.66,0.0,3.0,36.000000,70.103478,19.0,0.0,6988,24.8,87.0,0.0,36.000000,0.0,4199.0,239081.0,5.0,5.0,3.0,7.0,4.0,232093.0,70.00000,4.0,10.0,2534.0,52.0,28200.0,1.0,2.0,7.0,17.0,17077.0,17477.0,23.7,0.0,0.0,191.0,198.0,0.0,0.0,1.0,2.0,36.000000,0.000000,36.000000,7.0,4.0,6.0,8.0,17.0,55.0,13.0,31.0,6.0,19.0,0.0,0.0,0.0,7.0,89.0,0.0,0.0,0.0,267274.0,239081.0,22900.0,239074.0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,True

In [38]:
#create independent and dependent arrays
X = loans.drop('repayed', axis = 1).values
y = loans['repayed'].values

In [39]:
X

array([[4.500e+03, 3.600e+01, 1.000e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.000e+04, 6.000e+01, 4.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [6.600e+03, 3.600e+01, 1.000e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [1.800e+04, 6.000e+01, 1.000e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.795e+04, 6.000e+01, 1.000e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.500e+04, 6.000e+01, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

In [40]:
#get the dimentions of X
h, w = X.shape

In [41]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping

In [42]:
#apply stnadard scaler to X
scaler = StandardScaler()

X = scaler.fit_transform(X)

In [43]:
#create train test split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = 0.2, random_state = 3)

In [44]:
#instantiate sequntial model
model = Sequential()

#create model layers
model.add(Dense(128, input_shape = (w,), activation = 'sigmoid'))
model.add(Dense(256, activation = 'sigmoid'))
model.add(Dense(256, activation = 'sigmoid'))
model.add(Dense(256, activation = 'sigmoid'))
model.add(Dense(256, activation = 'sigmoid'))
model.add(Dense(1))
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

early_stopping = EarlyStopping(monitor = 'val_loss', patience = 5)

In [45]:
#run the model, saving the results to history
history = model.fit(X_train, y_train, 
                    epochs = 25,
                    validation_data = (X_val, y_val))

Train on 381264 samples, validate on 95317 samples
Epoch 1/25
381264/381264 [==============================] - 25s 65us/step - loss: 11.9178 - accuracy: 0.2274 - val_loss: 11.9570 - val_accuracy: 0.2248
Epoch 2/25
381264/381264 [==============================] - 24s 64us/step - loss: 11.9178 - accuracy: 0.2274 - val_loss: 11.9570 - val_accuracy: 0.2248
Epoch 3/25
381264/381264 [==============================] - 24s 62us/step - loss: 11.9178 - accuracy: 0.2274 - val_loss: 11.9570 - val_accuracy: 0.2248
Epoch 4/25
381264/381264 [==============================] - 24s 63us/step - loss: 11.9178 - accuracy: 0.2274 - val_loss: 11.9570 - val_accuracy: 0.2248
Epoch 5/25
 48288/381264 [==>...........................] - ETA: 20s - loss: 11.9102 - accuracy: 0.2279

KeyboardInterrupt:

In [ ]:
# Evaluate your model accuracy on the test set
accuracy = model.evaluate(X_test, y_test)[1]

# Print accuracy
print('Accuracy:', accuracy)